# MODEL:
#   PRETRAIN_CHOICE: 'imagenet'
#   PRETRAIN_PATH: '/root/basketball/jx_vit_base_p16_224-80ecf9dd.pth'  # 预训练权重路径
#   METRIC_LOSS_TYPE: 'triplet'
#   IF_LABELSMOOTH: 'off'
#   IF_WITH_CENTER: 'no'
#   NAME: 'transformer'
#   NO_MARGIN: True
#   DEVICE_ID: ('5')
#   TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
#   STRIDE_SIZE: [12, 12]
#   SIE_CAMERA: True
#   SIE_COE: 3.0
#   JPM: True
#   RE_ARRANGE: True

# INPUT:
#   SIZE_TRAIN: [256, 128]
#   SIZE_TEST: [256, 128]
#   PROB: 0.5 # random horizontal flip
#   RE_PROB: 0.5 # random erasing
#   PADDING: 10
#   PIXEL_MEAN: [0.5, 0.5, 0.5]
#   PIXEL_STD: [0.5, 0.5, 0.5]

# DATASETS:
#   NAMES: ('ballshow')
#   ROOT_DIR: ('/root/autodl-tmp')

# DATALOADER:
#   SAMPLER: 'softmax_triplet'
#   NUM_INSTANCE: 4
#   NUM_WORKERS: 8

# SOLVER:
#   OPTIMIZER_NAME: 'SGD'
#   MAX_EPOCHS: 60 #modified 120
#   BASE_LR: 0.008
#   IMS_PER_BATCH: 64
#   WARMUP_METHOD: 'linear'
#   LARGE_FC_LR: False
#   CHECKPOINT_PERIOD: 20 #modified 120
#   LOG_PERIOD: 50
#   EVAL_PERIOD: 20 #modified 120
#   WEIGHT_DECAY:  1e-4
#   WEIGHT_DECAY_BIAS: 1e-4
#   BIAS_LR_FACTOR: 2

# TEST:
#   EVAL: True
#   IMS_PER_BATCH: 256
#   RE_RANKING: False
#   WEIGHT: ''
#   NECK_FEAT: 'before'
#   FEAT_NORM: 'yes'

# OUTPUT_DIR: 'logs/BallShow_vit_transreid_stride'


MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/root/basketball/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('5')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: False
  RE_ARRANGE: False
  GLOBAL_LOCAL_FUSION:
    ENABLED: True
    NUM_PARTS: 3
    REDUCE_DIM: 256
    GLOBAL_TRIPLET_WEIGHT: 0.2
    LOCAL_TRIPLET_WEIGHT: 0.05
    AUX_ID_WEIGHT: 0.2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.10 # random erasing
  BASKETBALL_OCCLUSION:
    ENABLED: True
    PROB: 0.10
  RANDOM_ERASING:
    ENABLED: True
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('ballshow')
  ROOT_DIR: ('/root/autodl-tmp')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 50
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/BallShow_vit_transreid_stride_fusion'





